# compiler configuration
cc: clang
cxx: clang++
cflags: -std=c17 -O3 -Wall -Wextra
cxxflags: -std=c++17 -O3 -Wall -Wextra

# architecture flags
ext_flags:
    base: ""
    avx2: -mavx2
    neon: -mfpu=neon
