# compiler configuration
cc: clang
cxx: clang++
cflags: -std=c17 -O3 -Wall -Wextra
cxxflags: -std=c++17 -O3 -Wall -Wextra
ldflags: -lrt

asflags: -O3

# architecture flags
vflags:
    base: ""
    avx2: -mavx2 -mfma
    neon: -mfpu=neon
