# compiler configuration
cc: clang
cxx: clang++
cflags: -std=c17 -O3 -Wall -Wextra
cxxflags: -std=c++17 -O3 -Wall -Wextra
ldflags: -lm

levels:
    level1:
        - asum
        - axpy
        - dot
        - exo_copy
        - rot
        - scal

opt: ./vendor/llvm-project/build/bin/opt
mlir-opt: ./vendor/llvm-project/build/bin/mlir-opt
mlir-translate: ./vendor/llvm-project/build/bin/mlir-translate
