[project]
name = "exo-mlir"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.11.*"
dependencies = [
    "argparse>=1.4.0",
    "exo-lang==1.0.0",
    "matplotlib>=3.10.3",
    "pulp<2.8",
    "snakemake>=9.3.4",
    "xdsl",
]
scripts = { exo-mlir = "exomlir.main:main" }

[project.optional-dependencies]
exoblas = ["exoblas"]

[dependency-groups]
dev = [
    "filecheck>=1.0.2",
    "lit>=18.1.8",
    "llvmlite>=0.44.0",
    "matplotlib>=3.10.3",
    "pandas>=2.2.3",
    "pytest>=8.3.5",
    "ruff==0.11.9",
    "scipy>=1.15.3",
    "seaborn>=0.13.2",
]

[tool.uv]
package = true

[tool.uv.sources]
xdsl = { git = "https://github.com/kaylendog/xdsl", rev = "fc0b93e9126a585d522f78f7092afcc161fa588a" }
exoblas = { workspace = true }

[tool.uv.workspace]
members = ["./vendor/ExoBLAS"]

[tool.ruff]
target-version = "py310"

[tool.ruff.lint]
select = ["E", "F", "W", "I", "UP", "PT", "TID251", "INP"]
ignore = [
    "E741",  # https://beta.ruff.rs/docs/rules/ambiguous-variable-name/
    "PT006", # https://beta.ruff.rs/docs/rules/pytest-parametrize-names-wrong-type/
    "PT011", # https://beta.ruff.rs/docs/rules/pytest-raises-too-broad/
    "PT012", # https://beta.ruff.rs/docs/rules/pytest-raises-with-multiple-statements/
]

[tool.ruff.lint.pycodestyle]
max-line-length = 120
